import React from 'react';

const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
      id: 76600,
      title: 'Avatar: The Way of Water',
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28],
      popularity: 6789.789,
      release_date: '2022-12-14',
      video: false,
      vote_average: 7.736,
      vote_count: 6148,
    },
    {
      adult: false,
      backdrop_path: '/i8dshLvq4LE3s0v8PrkDdUyb1ae.jpg',
      id: 603692,
      title: 'John Wick: Chapter 4',
      original_language: 'en',
      original_title: 'John Wick: Chapter 4',
      overview:
        'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 80],
      popularity: 2803.482,
      release_date: '2023-03-22',
      video: false,
      vote_average: 8.2,
      vote_count: 495,
    },
    {
      adult: false,
      backdrop_path: '/vSUls0b7dNhC7tJoExF1MBYWWyh.jpg',
      id: 816904,
      title: 'Mummies',
      original_language: 'es',
      original_title: 'Momias',
      overview:
        'Through a series of unfortunate events, three mummies end up in present-day London and embark on a wacky and hilarious journey in search of an old ring belonging to the Royal Family, stolen by ambitious archaeologist Lord Carnaby.',
      poster_path: '/qVdrYN8qu7xUtsdEFeGiIVIaYd.jpg',
      media_type: 'movie',
      genre_ids: [16, 35, 10751],
      popularity: 446.228,
      release_date: '2023-01-05',
      video: false,
      vote_average: 6.786,
      vote_count: 49,
    },
    {
      adult: false,
      backdrop_path: '/uok4WE1sao8KAgvA1VqzJIy7Gun.jpg',
      id: 878375,
      title: 'On a Wing and a Prayer',
      original_language: 'en',
      original_title: 'On a Wing and a Prayer',
      overview:
        'After their pilot dies unexpectedly mid-flight, passenger Doug White must safely land a plane and save his entire family from insurmountable danger.',
      poster_path: '/wx3U05u7Yq7Nu9xw75LfhqaSPP5.jpg',
      media_type: 'movie',
      genre_ids: [18, 53],
      popularity: 19.575,
      release_date: '2023-04-06',
      video: false,
      vote_average: 6.0,
      vote_count: 2,
    },
    {
      adult: false,
      backdrop_path: '/cHywnrFfuDhDSST7lppYOAADmnt.jpg',
      id: 933419,
      title: 'Champions',
      original_language: 'en',
      original_title: 'Champions',
      overview:
        'A stubborn and hotheaded minor league basketball coach is forced to train a Special Olympics team when he is sentenced to community service.',
      poster_path: '/i46Gke8Kg3uH2K5eM0rDo4HzPtq.jpg',
      media_type: 'movie',
      genre_ids: [35],
      popularity: 38.016,
      release_date: '2023-03-09',
      video: false,
      vote_average: 6.3,
      vote_count: 30,
    },
    {
      adult: false,
      backdrop_path: '/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg',
      id: 82856,
      name: 'The Mandalorian',
      original_language: 'en',
      original_name: 'The Mandalorian',
      overview:
        'After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.',
      poster_path: '/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg',
      media_type: 'tv',
      genre_ids: [10765, 10759, 18],
      popularity: 1671.798,
      first_air_date: '2019-11-12',
      vote_average: 8.488,
      vote_count: 8681,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/qmEKe0AEsns2WXinbkGxlCxlTHq.jpg',
      id: 493529,
      title: 'Dungeons & Dragons: Honor Among Thieves',
      original_language: 'en',
      original_title: 'Dungeons & Dragons: Honor Among Thieves',
      overview:
        'A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic, but things go dangerously awry when they run afoul of the wrong people.',
      poster_path: '/6LuXaihVIoJ5FeSiFb7CZMtU7du.jpg',
      media_type: 'movie',
      genre_ids: [12, 14, 35],
      popularity: 412.073,
      release_date: '2023-03-24',
      video: false,
      vote_average: 7.7,
      vote_count: 38,
    },
    {
      adult: false,
      backdrop_path: '/2rfO7zh6e7rKaKCCvU4QrQwXLgv.jpg',
      id: 194704,
      name: 'The Big Door Prize',
      original_language: 'en',
      original_name: 'The Big Door Prize',
      overview:
        "A small town is forever changed when a mysterious machine appears, promising to reveal everyone's true potential. Soon residents start changing jobs, rethinking relationships, and questioning long-held beliefs—all in pursuit of a better future.",
      poster_path: '/w9iG3waL71PGlabP8kZe5Io6Igj.jpg',
      media_type: 'tv',
      genre_ids: [35],
      popularity: 38.332,
      first_air_date: '2023-03-28',
      vote_average: 7.5,
      vote_count: 6,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/26uCzg0yigXqjcM9dCGCDihoXLM.jpg',
      id: 129552,
      name: 'The Night Agent',
      original_language: 'en',
      original_name: 'The Night Agent',
      overview:
        'While monitoring an emergency line, a vigilant FBI agent answers a call that plunges him into a deadly conspiracy involving a mole at the White House.',
      poster_path: '/xjsx6rGEgHl2tUqkimo6Bz2KzVo.jpg',
      media_type: 'tv',
      genre_ids: [18, 9648],
      popularity: 677.446,
      first_air_date: '2023-03-23',
      vote_average: 7.8,
      vote_count: 80,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/884qeZrLDSqmxRElt1bZ4p8o4Vw.jpg',
      id: 220932,
      name: 'Unseen',
      original_language: 'en',
      original_name: 'Unseen',
      overview:
        'A house cleaner desperately searches for her husband as a dreaded criminal syndicate dredges up past tragedies and ultimately drives her to violence.',
      poster_path: '/lFKtgbboQohDi4tJNX1jp50WoXC.jpg',
      media_type: 'tv',
      genre_ids: [80, 18],
      popularity: 37.568,
      first_air_date: '2023-03-29',
      vote_average: 9.0,
      vote_count: 3,
      origin_country: ['ZA'],
    },
    {
      adult: false,
      backdrop_path: '/uUYd4Fl8J1ZwHda0A4V3QTKbWVu.jpg',
      id: 195841,
      name: 'Wellmania',
      original_language: 'en',
      original_name: 'Wellmania',
      overview:
        'When a health crisis forces Liv to rethink her “live fast, die young” attitude, she jumps into a wellness journey to get better — even if it kills her.',
      poster_path: '/c3F9aMUSwQovZkpEBynxBxN3keo.jpg',
      media_type: 'tv',
      genre_ids: [35, 18],
      popularity: 47.074,
      first_air_date: '2023-03-29',
      vote_average: 7.0,
      vote_count: 4,
      origin_country: ['AU'],
    },
    {
      adult: false,
      backdrop_path: '/3t9xDMXAytdWLPbrd97YsAQskxz.jpg',
      id: 219788,
      name: 'Unstable',
      original_language: 'en',
      original_name: 'Unstable',
      overview:
        'A biotech genius tries to bounce back from the depths of grief with help from his son, who works to escape his dad’s shadow and save the family business.',
      poster_path: '/yiMhsbuMYygbWnsrPbdp7PiMvvP.jpg',
      media_type: 'tv',
      genre_ids: [35, 18],
      popularity: 43.154,
      first_air_date: '2023-03-30',
      vote_average: 8.0,
      vote_count: 2,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg',
      id: 19995,
      title: 'Avatar',
      original_language: 'en',
      original_title: 'Avatar',
      overview:
        'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
      poster_path: '/jRXYjXNq0Cs2TcJjLkki24MLp7u.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 14, 878],
      popularity: 432.987,
      release_date: '2009-12-15',
      video: false,
      vote_average: 7.6,
      vote_count: 28738,
    },
    {
      adult: false,
      backdrop_path: '/ejEIt6TmywGov56dWDx0XWPP2NR.jpg',
      id: 156819,
      name: 'Rabbit Hole',
      original_language: 'en',
      original_name: 'Rabbit Hole',
      overview:
        'Nothing is what it seems when John Weir, a master of deception in the world of corporate espionage, is framed for murder by powerful forces with the ability to influence and control populations.',
      poster_path: '/zb5MArsrMxK4mSSLzUmbfcXAc60.jpg',
      media_type: 'tv',
      genre_ids: [18],
      popularity: 201.335,
      first_air_date: '2023-03-26',
      vote_average: 7.7,
      vote_count: 19,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/35slSk2fwFGDK8pZnPprOFKWxhV.jpg',
      id: 594767,
      title: 'Shazam! Fury of the Gods',
      original_language: 'en',
      original_title: 'Shazam! Fury of the Gods',
      overview:
        'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
      poster_path: '/3GrRgt6CiLIUXUtoktcv1g2iwT5.jpg',
      media_type: 'movie',
      genre_ids: [28, 35, 14],
      popularity: 720.071,
      release_date: '2023-03-15',
      video: false,
      vote_average: 6.848,
      vote_count: 279,
    },
    {
      adult: false,
      backdrop_path: '/a2tys4sD7xzVaogPntGsT1ypVoT.jpg',
      id: 804150,
      title: 'Cocaine Bear',
      original_language: 'en',
      original_title: 'Cocaine Bear',
      overview:
        'Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.',
      poster_path: '/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg',
      media_type: 'movie',
      genre_ids: [53, 35, 80, 27],
      popularity: 2781.045,
      release_date: '2023-02-22',
      video: false,
      vote_average: 6.561,
      vote_count: 538,
    },
    {
      adult: false,
      backdrop_path: '/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg',
      id: 100088,
      name: 'The Last of Us',
      original_language: 'en',
      original_name: 'The Last of Us',
      overview:
        'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.',
      poster_path: '/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
      media_type: 'tv',
      genre_ids: [18],
      popularity: 1849.192,
      first_air_date: '2023-01-15',
      vote_average: 8.768,
      vote_count: 2999,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/2HNbarpx0odHmPFh8A4ZPTxhend.jpg',
      id: 76331,
      name: 'Succession',
      original_language: 'en',
      original_name: 'Succession',
      overview:
        'Follow the lives of the Roy family as they contemplate their future once their aging father begins to step back from the media and entertainment conglomerate they control.',
      poster_path: '/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg',
      media_type: 'tv',
      genre_ids: [18],
      popularity: 257.049,
      first_air_date: '2018-06-03',
      vote_average: 8.145,
      vote_count: 568,
      origin_country: ['US'],
    },
    {
      adult: false,
      backdrop_path: '/vVpEOvdxVBP2aV166j5Xlvb5Cdc.jpg',
      id: 458156,
      title: 'John Wick: Chapter 3 - Parabellum',
      original_language: 'en',
      original_title: 'John Wick: Chapter 3 - Parabellum',
      overview:
        'Super-assassin John Wick returns with a $14 million price tag on his head and an army of bounty-hunting killers on his trail. After killing a member of the shadowy international assassin’s guild, the High Table, John Wick is excommunicado, but the world’s most ruthless hit men and women await his every turn.',
      poster_path: '/ziEuG1essDuWuC5lpWUaw1uXY2O.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 80],
      popularity: 795.388,
      release_date: '2019-05-15',
      video: false,
      vote_average: 7.44,
      vote_count: 8872,
    },
    {
      adult: false,
      backdrop_path: '/7dzngS8pLkGJpyeskCFcjPO9qLF.jpg',
      id: 245891,
      title: 'John Wick',
      original_language: 'en',
      original_title: 'John Wick',
      overview:
        'Ex-hitman John Wick comes out of retirement to track down the gangsters that took everything from him.',
      poster_path: '/nCzzQKGijVzfGFg42id7uDLOjY5.jpg',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 534.017,
      release_date: '2014-10-22',
      video: false,
      vote_average: 7.396,
      vote_count: 16949,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
